### ISSUE TITLE
Warning: htmlentities() expects parameter 1 to be string

### ISSUE THREAD

**Issue by rikmendes** [mapkyca/IdnoOpenGraph#3]
What I did : updated & activated IdnoOpenGraph Plugin on Known 0.9.1

this is what I get when the post is saved : 
```
Warning: htmlentities() expects parameter 1 to be string, array given in rmendes.net/IdnoPlugins/IdnoOpenGraph/templates/default/entity/OpenGraph.tpl.php on line 20

Warning: htmlentities() expects parameter 1 to be string, array given in /rmendes.net/IdnoPlugins/IdnoOpenGraph/templates/default/entity/OpenGraph.tpl.php on line 21
```
![screenshot_52](https://cloud.githubusercontent.com/assets/12155003/13460567/ae4912b2-e07b-11e5-8836-b0a0d8f8bfdc.png)

**Comment by rikmendes** [comment]
this was probably related to something that got fixed, because I tested this and the error is gone.

**Comment by rikmendes** [comment]
I keep getting these errors on different URL's - I just don't understand why some do it (https://www.rmendes.net/2016/how-to-boost-your-twitter-engagement-following-in-5-simple) , others don't (like https://www.rmendes.net/2016/les-violences-polici%C3%A8res-sont-la-graine-qui-fera-grandir-la)  and some others simply display a grey rectangle without any "oembed" displayed look here : https://www.rmendes.net/2016/open-whisper-systems-blog-reflections-the-ecosystem-is-moving

**Comment by mapkyca** [comment]
<a href="https://github.com/mapkyca/IdnoOpenGraph/issues/3" class="u-in-reply-to"></a>Good to hear!
