### ISSUE TITLE
Notice: Undefined index

### ISSUE THREAD

**Issue by benborges** [mapkyca/IdnoOpenGraph#6]
Notice: Undefined index: og:title in /sites/1-m.cc/www/IdnoPlugins/IdnoOpenGraph/templates/default/entity/OpenGraph.tpl.php on line 20

Notice: Undefined index: og:description in /sites/1-m.cc/www/IdnoPlugins/IdnoOpenGraph/templates/default/entity/OpenGraph.tpl.php on line 21

Live here : 
https://1-m.cc/2016/agile-development-and-experience-design-thoughtworks

not sure why some bookmarks output this error and others don't... ex : https://1-m.cc/2016/ttip-under-pressure-what-are-the-forecasts-stopttip

**Comment by danito** [comment]
I still get this kind of error:
```php
 mod_fcgid: stderr: Known (nxd4n.nixekinder.be): warning - PHP [2] htmlentities() expects parameter 1 to be string, array given in /var/www/virtual/nxd4n/html/IdnoPlugins/IdnoOpenGraph/templates/default/entity/OpenGraph.tpl.php:25

```
